### ISSUE TITLE
Illegal argument value: Positional arguments were provided ',barcodes.csv}' but no positional argument is defined for this tool.

### ISSUE THREAD

**Issue by Tijs-dot** [ucagenomix/sicelore-2.1#10]
Hi, I am trying to perform the step 4 Option (a) of the Sicelore pipeline. For this first test I used a bam with only one chromosome.

java -jar -Xmx40g Jar/Sicelore-2.1.jar IsoformMatrix -I ${umidir}chr19_only.primary_only.passed.Parsed.bam -GENETAG GE -UMITAG U8 -CELLTAG BC -REFFLAT $gencoderefflat -CSV ${siceloredir}barcodes.csv -DELTA 2 -MAXCLIP 150 -METHOD STRICT -AMBIGUOUS_ASSIGN false -OUTDIR $siceloredir -PREFIX sicelore

However, I am receiving following error:
Illegal argument value: Positional arguments were provided ',barcodes.csv}' but no positional argument is defined for this tool.

Please let me know if I need to provide you with further information.

Thanks,
Tijs

**Comment by bfxomics** [comment]
Hi,
never seen this kind of error message, please double check your command line:
https://gatk.broadinstitute.org/hc/en-us/community/posts/360076948391--No-positional-argument-is-defined-Error-in-HaplotypeCaller
https://gatk.broadinstitute.org/hc/en-us/community/posts/360077380972-ApplyBQSR-no-positional-argument-is-defined-for-this-tool

or try to provide the full path to the files

best,
kevin

**Comment by Tijs-dot** [comment]
Hi Kevin, providing full paths solved the issue. 

Thanks for the quick solution!
Tijs
