### ISSUE TITLE
Get stuck in step 1

### ISSUE THREAD

**Issue by dontwantcode** [ucagenomix/sicelore-2.1#2]
Hi,
I was trying to apply sicelore2 to a simulated fastq file, but it just got stuck at step 1 and never moved further, here is the log:
```
### Step 1 - Adapter search, stranding, barcode assignment to reads ###

version=2.1
build.date=2022-11-04T09:24:14Z
READING config FILE: config.xml
Trying current working directory: /home/software/scNaUMIseq/sicelore2.1/config.xml
Not found trying application root:/home/software/scNaUMIseq/sicelore2.1/Jar/config.xml
O.K. Found and using /home/software/scNaUMIseq/sicelore2.1/Jar/config.xml
1 Files found
Using Barcodes from: /home/data/BarcodeMatch/FT/FT_cells.txt
Cellranger list of barcodes was supplied --> skipping 1st pass (Search for used barcodes)
Pass 2- stranding reads, assigning barcodes

All threads submitted - waiting for threads to terminate
Waiting for writer to terminate
```
Is there any possible reason leading to this. I appreciate it if you have any thoughts about this situation.
Thanks!

**Comment by RainerWaldmann** [comment]
Hi,


Before the "All threads submitted - waiting for threads to terminate" it should show the progress
Something like:
  1% [=>                                                                                                   ]   241/24164 files, 1148095 reads   2% [==>                                                                                                  ]   482/24164 files, 2296485 reads   .........

How many reads did you try to scan ?
Were any fastqs generated in "failed" and "passed" output folders ?
How much RAM does the computer have ? (Just to exclude a JVM stuck in garbage collection)

Rainer

**Comment by dontwantcode** [comment]
Hi Rainer,
Thanks for your feedback!
As it's a small simulated dataset, which includes 23664 reads, I just use one thread with max limit of 20G memory.
There did exsit the output of `fastq.gz` files in the `passed` and `failed` folders. But I didn't see anything like the progress in my log file.

Thanks!

**Comment by RainerWaldmann** [comment]
Hi,

We could not reproduce your problem with our data.
You definitely have sufficient RAM.
Since you used a small simulated dataset, you could share the reads and the FT_cells.txt file with us. 

Rainer

**Comment by dontwantcode** [comment]
Hi Rainer,
Sure, I have uploaded my files to google drive, and here is the share link
https://drive.google.com/drive/folders/11P4r24DxEHM1tCm66vzPn0KXCoXEi0N6?usp=sharing.

Thanks
