### ISSUE TITLE
NanoporeBC_UMI_finder find nothing for 3' VISIUM sequencing

### ISSUE THREAD

**Issue by yuntianf** [ucagenomix/sicelore-2.1#30]
Hi,
Thanks for the great tool.
I was applying the sicelore2.1 to process my VISIUM data, which is sequenced by 3' 10X kit. 
My order is:
`java -jar -Xmx23G Jar/NanoporeBC_UMI_finder-2.1.jar scanfastq -g $barcode -d $fastqdir -o $readscandir --bcEditDistance 2 --compress -p 10`
However this step didn't return me with any valid reads and the log is:
```
version=2.1
build.date=2023-10-16T12:45:44Z
READING config FILE: config.xml
Trying current working directory: /home/software/sicelore2/sicelore-2.1/config.xml
Not found trying application root:/home/software/sicelore2/sicelore-2.1/Jar/config.xml
O.K. Found and using /home/software/sicelore2/sicelore-2.1/Jar/config.xml
ESC[1;31mNO INPUT FILES FOUNDESC[0m
find: ‘/home/sicelore2//readscan//passed/’: No such file or directory
pigz: skipping: <stdin> empty
```
I'm sure the barcode file input is correct as I also processed this data with FLAMES and it returned a valid result. And the sequences also have valid 3' adapter sequence as screenshot below:
![image](https://github.com/user-attachments/assets/ea13581d-9ab6-4904-9741-b9730747c79d)

Could you help me figure out what the possible reason for this case?

Thanks

**Comment by cobioda** [comment]
hi,

Thanks for giving a try to sicelore instead of flammes, this is a very good idea !
Just seems to be a "No such file or directory" error, please check the path given on the command line, probably $readscandir needs to be a valid directory.

best,

**Comment by yuntianf** [comment]
Hi,
Thanks for your response, I'm sure the path is valid, and the problem is that `NanoporeBC_UMI_finder-2.1.jar` returnd an empty  `fastq_pass.fastq.gz`  and there is nothing in the `readscan` folder. Here attached my scripts:
```
readonly analysisdir=$HOME/LongReadsdata/VISIUM_Nanopore/sicelore2/
readonly readscandir=${analysisdir}/readscan/
readonly mappingdir=${analysisdir}/mapping/
readonly umidir=${analysisdir}/umis/
readonly tmpdir=${analysisdir}/tmp/
readonly siceloredir=${analysisdir}/out/

readonly fastqdir=$HOME/LongReadsdata/VISIUM_Nanopore/fastq/
readonly barcode=$HOME/LongReadsdata/VISIUM_Nanopore/barcodes.txt

readonly refer=${HOME}/reference/refdata-gex-mm10-2020-A//fasta/genome.fa
readonly junc_bed=${HOME}/reference/annotation/mouse/mm10/gencode.vM10.annotation.bed
readonly refFlat=${HOME}/reference/annotation/mouse/mm10/gencode.vM10.annotation.gtf

mkdir -p $analysisdir
mkdir -p $readscandir
mkdir -p $umidir
mkdir -p $mappingdir
mkdir -p $siceloredir
mkdir -p $tmpdir

# need at least Java >= 12
java=java
minimap2=minimap2
samtools=samtools

if [ -z "$java" ] || [ -z "$samtools" ] || [ -z "$minimap2" ]
then
    echo -e "\nMissing path to required softwares:"
    echo -e "\tjava=$java"
    echo -e "\tsamtools=$samtools"
    echo -e "\tminimap2=$minimap2"
    echo -e "\nPlease update your \$PATH and rerun.\n\n"
    exit
fi


### Step 1 - Adapter search, stranding, barcode assignment to reads ###
$java -jar -Xmx24G Jar/NanoporeBC_UMI_finder-2.1.jar scanfastq -d $fastqdir -o $readscandir --bcEditDistance 2 --compress -p 10 -g $barcode
find ${readscandir}/passed/ -type f -name '*' | xargs pigz -dc |  pigz > ${analysisdir}fastq_pass.fastq.gz
```

Just in case if you want to reproduce the error, I also subsampled my data and upload it here:
https://drive.google.com/drive/folders/11P4r24DxEHM1tCm66vzPn0KXCoXEi0N6?usp=drive_link

**Comment by RainerWaldmann** [comment]
Hi

apparently there are no fastq files in your -d $fastqdir input directory.

version=2.1
build.date=2023-10-16T12:45:44Z
READING config FILE: config.xml
Trying current working directory: /home/software/sicelore2/sicelore-2.1/config.xml
Not found trying application root:/home/software/sicelore2/sicelore-2.1/Jar/config.xml
O.K. Found and using /home/software/sicelore2/sicelore-2.1/Jar/config.xml
**ESC[1;31mNO INPUT FILES FOUNDESC[0m**

**Comment by yuntianf** [comment]
Hi,

I add a command line `ls -lh $fastqdir` at the beginning to list the file, here is the log:
```
list all files under the fastqdir:
total 33G
-rw-rw-r-- 1 yuntianf 33G Nov  5 11:33 MOB.fq.gz

version=2.1
build.date=2023-10-16T12:45:44Z
READING config FILE: config.xml
Trying current working directory: /home/software/sicelore2/sicelore-2.1/config.xml
Not found trying application root:/home/software/sicelore2/sicelore-2.1/Jar/config.xml
O.K. Found and using /home/software/sicelore2/sicelore-2.1/Jar/config.xml
ESC[1;31mNO INPUT FILES FOUNDESC[0m
find: ‘/home/sicelore2//readscan//passed/’: No such file or directory
pigz: skipping: <stdin> empty
took 2 seconds to complete barcode match
```

**Comment by RainerWaldmann** [comment]
MOB.fq.gz
rename your file to MOB.fastq.gz !

the default regex for input files is ".{1,}\.fastq(\.gz)?"  -> .fastq or .fastq.gz
If you want to use different extensions you can provide another pattern with the <-–pattern> option.


from the doc
-d,--inDir

<,> separated list of directories to start file search. starting at this directory, takes recursively (if --nonrecursive is not set) fastq files with names that match the RegEx pattern provided in <-–pattern> option, **defaults to files ending with .fastq or fastq.gz**. Regex: "".{1,}\.fastq(\.gz)?"

**Comment by yuntianf** [comment]
Thanks for your quick repsonse!
Sorry I missed this point, I will close this issue.
